# Generated by Django 5.1 on 2024-08-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='watermarked',
            field=models.BooleanField(default=False),
        ),
    ]
